<?php

namespace App\Models;

use Carbon\Carbon;
use Faker\Provider\Base;
use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    protected $fillable = [
        'vendor_id',
        'date',
        'name',
        'contact_person',
        'contact_tel',
        'status',
        'note',
        'end_date',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->tracking_number = Carbon::now()->format('mdy') . Base::numerify('####');
        });
    }

    public function purchaseProducts()
    {
        return $this->hasMany(PurchaseProduct::class);
    }
}
